repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.83.5 
    hooks:
      - id: trufflehog
        args: [--only-verified]

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: install-requirements
        name: Install Requirements
        entry: pip install -r requirements.txt
        language: system
        types: [python]
        pass_filenames: false